# This is a basic workflow to help you get started with Actions
# This is my cat
name: mycatapp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
      - name: Docker Login
        uses: docker/login-action@v2.1.0

        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker build . ghcr.io/dianaviktorova/mycatapp:diana:latest
          docker run ghcr.io/dianaviktorova/mycatapp:diana:latest
          docker push ghcr.io/dianaviktorova/mycatapp:tagname
